#ifndef __APP_VEHICLE_CONFIG_H
#define __APP_VEHICLE_CONFIG_H

#include <stdint.h>

/*
 * Current-product vehicle defaults.
 *
 * Runtime `g_orin_*` variables still exist for Keil Watch tuning. These macros
 * are the single source for reset-time defaults when those variables are zero.
 */
#define APP_ORIN_PWM_ENABLE_DEFAULT                 1U
#define APP_ORIN_PWM_TIMEOUT_DEFAULT_MS           250U

#define APP_ORIN_ACKERMANN_WHEELBASE_MM           600U
#define APP_ORIN_ACKERMANN_TRACK_WIDTH_MM         500U
#define APP_ORIN_ACKERMANN_WHEEL_RADIUS_MM        115U
#define APP_ORIN_ACKERMANN_MAX_STEERING_MRAD      349U
#define APP_ORIN_MIN_COMMAND_SPEED_MMPS            300U
#define APP_ORIN_ACKERMANN_MIN_VX_MMPS             APP_ORIN_MIN_COMMAND_SPEED_MMPS

#define APP_ORIN_VX_SCALE_PERMILLE               1000U
#define APP_ORIN_VX_FORWARD_CAP_MMPS            10000U
#define APP_ORIN_VX_REVERSE_CAP_MMPS             3000U
#define APP_ORIN_VX_DEADBAND_MMPS                  APP_ORIN_MIN_COMMAND_SPEED_MMPS
#define APP_ORIN_VX_MAX_DEFAULT_MMPS            10000U

#define APP_ORIN_MIN_FORWARD_VX_MMPS               APP_ORIN_MIN_COMMAND_SPEED_MMPS
#define APP_ORIN_MIN_REVERSE_VX_MMPS               APP_ORIN_MIN_COMMAND_SPEED_MMPS

#define APP_HALL_SPEED_LIMIT_MMPS               12000U
#define APP_HALL_SPEED_LIMIT_RELEASE_MMPS       10500U
#define APP_HALL_SPEED_LIMIT_CONFIRM_SAMPLES        3U
#define APP_HALL_GLITCH_FAULT_CONFIRM_EVENTS         3U

#define APP_ESC_SPEED_LIMIT_MMPS                12000U
#define APP_ESC_SPEED_LIMIT_RELEASE_MMPS        10500U
#define APP_ESC_SPEED_LIMIT_CONFIRM_SAMPLES         3U
#define APP_ESC_SPEED_CALIBRATION_VALID_DEFAULT       1U
#define APP_ESC_LOW_GEAR_WHEEL_RPM_PER_RAW_DEFAULT 0.14115f
#define APP_ESC_SPEED_FRESH_TIMEOUT_MS_DEFAULT      250U
#define APP_ESC_TRACKING_BRAKE_VALID_DEFAULT        1U
#define APP_ESC_TRACKING_BRAKE_KP_DEFAULT        0.50f
#define APP_ESC_TRACKING_BRAKE_MAX_DEFAULT       0.70f
#define APP_ESC_TRACKING_BRAKE_ENTER_ERROR_MPS_DEFAULT 0.20f
#define APP_ESC_TRACKING_BRAKE_RELEASE_ERROR_MPS_DEFAULT 0.10f

#define APP_ESC_MOTION_CALIBRATION_VALID_DEFAULT      1U
#define APP_ESC_MOTION_MAGNITUDE_CONFIG_VALID_DEFAULT APP_ESC_SPEED_CALIBRATION_VALID_DEFAULT
#define APP_ESC_MOTION_WHEEL_RPM_PER_RAW_VALID_DEFAULT APP_ESC_SPEED_CALIBRATION_VALID_DEFAULT
#define APP_ESC_MOTION_WHEEL_RADIUS_VALID_DEFAULT     1U
#define APP_ESC_MOTION_POLE_PAIRS_VALID_DEFAULT       0U
#define APP_ESC_MOTION_GEAR_RATIO_VALID_DEFAULT       0U
#define APP_ESC_MOTION_WHEEL_RATIO_VALID_DEFAULT      0U
#define APP_ESC_MOTION_WHEEL_CIRCUMFERENCE_VALID_DEFAULT 0U
#define APP_ESC_MOTION_TELEMETRY_TIMEOUT_VALID_DEFAULT 1U
#define APP_ESC_MOTION_STOP_CONFIG_VALID_DEFAULT      1U
#define APP_ESC_MOTION_STOPPED_THRESHOLD_VALID_DEFAULT 1U
#define APP_ESC_MOTION_STOPPED_SAMPLES_VALID_DEFAULT   1U
#define APP_ESC_MOTION_STOPPED_COVERAGE_VALID_DEFAULT  1U
#define APP_ESC_MOTION_MOTOR_POLE_PAIRS_DEFAULT        0U
#define APP_ESC_MOTION_GEAR_RATIO_DEFAULT           0.0f
#define APP_ESC_MOTION_WHEEL_RATIO_DEFAULT          0.0f
#define APP_ESC_MOTION_WHEEL_CIRCUMFERENCE_M_DEFAULT 0.0f
#define APP_ESC_MOTION_WHEEL_RPM_PER_RAW_DEFAULT APP_ESC_LOW_GEAR_WHEEL_RPM_PER_RAW_DEFAULT
#define APP_ESC_MOTION_WHEEL_RADIUS_M_DEFAULT       0.115f
#define APP_ESC_MOTION_TELEMETRY_TIMEOUT_MS_DEFAULT APP_ESC_SPEED_FRESH_TIMEOUT_MS_DEFAULT
#define APP_ESC_MOTION_STOPPED_THRESHOLD_MPS_DEFAULT 0.05f
#define APP_ESC_MOTION_STOPPED_MIN_SAMPLES_DEFAULT     3U
#define APP_ESC_MOTION_STOPPED_MIN_COVERAGE_MS_DEFAULT 150U

#define APP_MODE2_DRIVE_CALIBRATION_VALID_DEFAULT       1U
#define APP_MODE2_DRIVE_BRAKE_CALIBRATION_VALID_DEFAULT 1U
#define APP_MODE2_DRIVE_FIRST_STRIKE_CALIBRATION_VALID_DEFAULT 1U
#define APP_MODE2_DRIVE_NEUTRAL_DWELL_VALID_DEFAULT     1U
#define APP_MODE2_DRIVE_REVERSAL_TIMEOUT_VALID_DEFAULT  1U
#define APP_MODE2_DRIVE_BRAKE_REQUEST_DEFAULT        0.70f
#define APP_MODE2_DRIVE_REVERSE_FIRST_STRIKE_REQUEST_DEFAULT 0.70f
#define APP_MODE2_DRIVE_REVERSE_FIRST_STRIKE_MIN_MS_DEFAULT 100U
#define APP_MODE2_FWD_TO_REV_BRAKE_REQUEST_DEFAULT       0.70f
#define APP_MODE2_REV_TO_FWD_BRAKE_REQUEST_DEFAULT       0.70f
#define APP_MODE2_FWD_TO_REV_BRAKE_HOLD_MS_DEFAULT        100U
#define APP_MODE2_REV_TO_FWD_BRAKE_HOLD_MS_DEFAULT        100U
#define APP_MODE2_DRIVE_NEUTRAL_DWELL_MS_DEFAULT        100U
#define APP_MODE2_DRIVE_REVERSAL_TIMEOUT_MS_DEFAULT    5000U
#define APP_MODE2_FWD_TO_REV_QUALIFY_DELTA_US_DEFAULT   100U
#define APP_MODE2_REV_TO_FWD_QUALIFY_DELTA_US_DEFAULT   100U
#define APP_MODE2_BRAKE_PWM_VALID_DEFAULT               1U
#define APP_MODE2_BRAKE_PWM_CENTER_US_DEFAULT        1500U
#define APP_MODE2_BRAKE_PWM_FULL_US_DEFAULT          1350U
#define APP_MODE2_FORWARD_BRAKE_PWM_VALID_DEFAULT       1U
#define APP_MODE2_FORWARD_BRAKE_PWM_CENTER_US_DEFAULT 1500U
#define APP_MODE2_FORWARD_BRAKE_PWM_FULL_US_DEFAULT   1650U

#define APP_ORIN_ACCEL_LIMIT_MMPS2               4000U
#define APP_ORIN_STEERING_RATE_LIMIT_MRADPS       900U

#define APP_SPEED_PI_ENABLE_DEFAULT                 1U
#define APP_SPEED_PI_KP_DEFAULT_US_PER_MPS       20.0f
#define APP_SPEED_PI_KI_DEFAULT_US_PER_MPS_S      0.0f
#define APP_SPEED_PI_TRIM_LIMIT_US                 12U

#define APP_ORIN_ESC_CENTER_US                   1500U
#define APP_ORIN_ESC_RANGE_US                     500U
#define APP_ORIN_ESC_FORWARD_START_US            1560U
#define APP_ORIN_ESC_REVERSE_START_US            1440U
#define APP_ORIN_ESC_FORWARD_MAX_US              1650U
#define APP_ORIN_ESC_REVERSE_MAX_US              1350U

#define APP_ORIN_SERVO_CENTER_US                 1500U
#define APP_ORIN_SERVO_RANGE_US                   395U
/* Standard positive tire angle is left; this chassis needs increasing PWM. */
#define APP_ORIN_STEERING_PWM_DIRECTION_SIGN        (+1)

#if (APP_ORIN_STEERING_PWM_DIRECTION_SIGN != 1) && \
	(APP_ORIN_STEERING_PWM_DIRECTION_SIGN != -1)
#error "APP_ORIN_STEERING_PWM_DIRECTION_SIGN must be +1 or -1"
#endif

#if APP_HALL_GLITCH_FAULT_CONFIRM_EVENTS < 2U
#error "APP_HALL_GLITCH_FAULT_CONFIRM_EVENTS must reject a single glitch"
#endif

#define APP_RC_VALID_MIN_US                       900U
#define APP_RC_VALID_MAX_US                      2100U
#define APP_RC_FRAME_MIN_US                      5000U
#define APP_RC_FRAME_MAX_US                     30000U
#define APP_RC_GLITCH_FREEZE_MS                   100U
#define APP_RC_SIGNAL_TIMEOUT_MS                  100U
#define APP_RC_PWM_FOLLOW_RAW_DEFAULT               0U

#define APP_RC_DEBOUNCE_ENABLE_DEFAULT              1U
#define APP_RC_DEBOUNCE_DEADBAND_US                 5U
#define APP_RC_DEBOUNCE_SMOOTH_DIV                  4U
#define APP_RC_THROTTLE_NEUTRAL_HOLD_US            25U
#define APP_RC_THROTTLE_JUMP_CONFIRM_US            40U
#define APP_RC_STEERING_JUMP_CONFIRM_US            80U
#define APP_RC_JUMP_CONFIRM_SAMPLES                 2U

#define APP_RC_OVERRIDE_CENTER_US                 1500U
#define APP_RC_OVERRIDE_ENTER_THRESHOLD_US          60U
#define APP_RC_OVERRIDE_EXIT_THRESHOLD_US           40U
#define APP_RC_OVERRIDE_ENTER_SAMPLES               2U
#define APP_RC_OVERRIDE_RELEASE_HOLD_MS           500U

#define APP_RC_GUARD_ENABLE_DEFAULT                 0U
#define APP_RC_GUARD_ACTIVE_HIGH_DEFAULT            1U
#define APP_RC_GUARD_ACTIVE_LOW_THRESHOLD_US     1300U
#define APP_RC_GUARD_ACTIVE_HIGH_THRESHOLD_US    1700U

#endif
